-- CreateTable
CREATE TABLE "userSurvey1" (
    "id" TEXT NOT NULL,
    "lastUpdate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "termsOfService" BOOLEAN NOT NULL DEFAULT false,
    "privacyPolicy" BOOLEAN NOT NULL DEFAULT false,
    "region" TEXT,
    "q1" TEXT,
    "q2" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "q3" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "q4" TEXT,
    "q5" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "q6" TEXT,
    "q7" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "q8" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "q9" TEXT,
    "q10" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "q11" TEXT,
    "q12" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "q13" TEXT,
    "q14" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "q15" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "q16" TEXT,
    "q17" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "q18" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "q19" TEXT,
    "q20" TEXT[] DEFAULT ARRAY[]::TEXT[],

    CONSTRAINT "userSurvey1_pkey" PRIMARY KEY ("id")
);
